### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by inukaze** [Solybum/Aselia#1]
Hi there, i just want to Request a Feature : Intranet

I want the posibility to make the server and not have any problem to start server and connect the clients to that specific server ip. 

Because i had days trying to connect in intranet the "Ephinea" offline server, but looks like are make to not work on internet mode, just SinglePlayer or Internet mode. But i want to play on a friend's house, they don't have internet access, and us don't like play games like this on SinglePlayer.

If possible you can add a mini tool to change the ip the client of phantasy star blue burst is connecting because i had make Hexadecimal edition just for change the ip of the target server.

Well that's is all , thank you for read

**Comment by Solybum** [comment]
For that you just have to set the right (internal) IP address, the one given to the computer hosting the server by the router.

Changing the IP address of the client is out of the scope for this repo.
We have another repo which is for changes in the client performed via an "injected" DLL
https://github.com/Solybum/Blue-Burst-Patch-Project

Although that project is still a work in progress, eventually that will help you do that.

**Comment by inukaze** [comment]
Thank you very much, i had download Tethealla Server, and config manually the ip and works fine. thank for that tool :D
